
# CI Workflow is used to test stability of changes prior to merging
name: CI-Workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Meta
      - uses: actions/checkout@v2
      # Tasks
      - name: Install npm dependencies
        run: npm install
      - name: Build application
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      # Meta
      - uses: actions/checkout@v2
      # Tasks
      - name: Install npm dependencies
        run: npm install
      - name: Test application
        run: npm run test